// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.user_id", "a5636671-ccb9-4e6c-85d9-2d52c4e68f9f");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1552643735);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1552643855);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1552678551);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1552671471);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1552671231);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1552643615);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1552644095);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1552643975);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 389120);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1552642049);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4f355572-175d-460b-83b6-99779489116a}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1552588200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1552678477159");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1552680257159");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1552678422998");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1552682022998");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1552671212");
user_pref("browser.slowStartup.averageTime", 12015);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190128144255");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1552643485862");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "2c7fa0f27ea240fa8a27fcaafcfd7ca4");
user_pref("extensions.blocklist.lastModified", "Thu, 14 Mar 2019 12:52:21 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1552643737);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190128144255");
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pocket.settings.test.panelSignUp", "control");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{0df4cdec-3673-472c-a063-23c298dd7d98}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"},\"webcompat@mozilla.org\":{\"version\":\"3.0.1\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"c25a1623-bd8b-48be-9cc1-bed60b10a132\",\"screenshots@mozilla.org\":\"82fb2e6c-44b0-4a87-b12b-e757436f1b93\",\"webcompat-reporter@mozilla.org\":\"d42e224a-4eae-4016-824c-3f0d7dcd9d0d\",\"webcompat@mozilla.org\":\"6379d573-6432-42e7-ac36-a015a2c2c5a6\",\"fxmonitor@mozilla.org\":\"d067b12a-4bf7-497d-87cc-4c27c518306d\"}");
user_pref("font.internaluseonly.changed", false);
user_pref("idle.lastDailyNotification", 1552644124);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1552643508);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190128144255");
user_pref("media.gmp-manager.lastCheck", 1552643507);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1552644150);
user_pref("places.history.expiration.transient_current_max_pages", 109780);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "186c95db-e52c-4263-a718-cc4777b3c184");
user_pref("security.sandbox.plugin.tempDirSuffix", "e3c0cfd3-b003-4218-b6f1-059e3657cae3");
user_pref("services.blocklist.addons.checked", 1552643799);
user_pref("services.blocklist.gfx.checked", 1552643799);
user_pref("services.blocklist.onecrl.checked", 1552643799);
user_pref("services.blocklist.pinning.checked", 1552643799);
user_pref("services.blocklist.plugins.checked", 1552643799);
user_pref("services.settings.clock_skew_seconds", -174);
user_pref("services.settings.last_update_seconds", 1552643788);
user_pref("services.settings.main.language-dictionaries.last_check", 1552643799);
user_pref("services.settings.main.onboarding.last_check", 1552643799);
user_pref("services.settings.main.sites-classification.last_check", 1552643799);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1552644146);
user_pref("toolkit.startup.last_success", 1552671196);
user_pref("toolkit.telemetry.cachedClientID", "6083d92f-68f4-4355-a151-7070bb17bfe8");
user_pref("toolkit.telemetry.previousBuildID", "20190128144255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
